services:
   web:
      image: web
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "81:80"
      links:
        - db
      command: bash -c "a2enmod rewrite && apache2-foreground"
      volumes:
        - ./app:/var/www/html/
        - ./config/custom.php.ini:/etc/php5/apache2/conf.d/custom.php.ini

   db:
     image: mariadb:10.8.2
     restart: always
     volumes:
       - ./mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: database
     ports:
       - "8889:3306"

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     links:
       - db
     ports:
       - 8890:80
     environment:
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: database
